import { execFileSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
// Import the shared type instead of redeclaring — keeps the strict union from
// helpers/sandbox-fixture.ts authoritative across the script and the consumers.
import type { SandboxFixture } from '../e2e/real/helpers/sandbox-fixture';

const OWNER = 'prpande';
const REPO = 'prism-sandbox';
const FIXTURE_NAMES = ['happy', 'foreign', 'lost-response', 'stale-oid'] as const;

function gh<T>(args: string[]): T {
  const out = execFileSync('gh', args, { encoding: 'utf8' });
  return JSON.parse(out) as T;
}

function viewerLogin(): string {
  const result = gh<{ data: { viewer: { login: string } } }>([
    'api',
    'graphql',
    '-f',
    'query={ viewer { login } }',
  ]);
  return result.data.viewer.login;
}

function masterHeadOid(): string {
  const result = gh<{ data: { repository: { ref: { target: { oid: string } } } } }>([
    'api',
    'graphql',
    '-f',
    `query={ repository(owner: "${OWNER}", name: "${REPO}") { ref(qualifiedName: "refs/heads/master") { target { oid } } } }`,
  ]);
  return result.data.repository.ref.target.oid;
}

function branchExists(branch: string): boolean {
  // One round-trip: gh api throws on non-zero exit (e.g. 404 for missing branch);
  // catch the throw and return false. Don't pipe `--silent` (gh api doesn't take that flag).
  try {
    execFileSync('gh', ['api', `repos/${OWNER}/${REPO}/branches/${branch}`], {
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    return true;
  } catch {
    return false;
  }
}

function ensureBranchAtSeed(
  branch: string,
  _name: string,
): { baseOid: string; anchorFile: string; anchorLine: number } {
  const anchorFile = 'src/Calc.cs';
  const anchorLine = 3;
  // Seed content — a 5-line C# stub with line 3 as the anchorable line.
  // base64-encoded for createCommitOnBranch (GraphQL FileAddition.contents is Base64String).
  const seedContent = `namespace Sandbox;
public static class Calc
{
    public static int Add(int a, int b) => a + b;
    public static int Sub(int a, int b) => a - b;
}
`;
  const contentBase64 = Buffer.from(seedContent, 'utf8').toString('base64');

  if (!branchExists(branch)) {
    // Create branch from master head, then commit the anchor file via createCommitOnBranch.
    const head = masterHeadOid();
    gh<unknown>([
      'api',
      '-X',
      'POST',
      `repos/${OWNER}/${REPO}/git/refs`,
      '-f',
      `ref=refs/heads/${branch}`,
      '-f',
      `sha=${head}`,
    ]);
    gh<unknown>([
      'api',
      'graphql',
      '-f',
      `query=mutation { createCommitOnBranch(input: { branch: { repositoryNameWithOwner: "${OWNER}/${REPO}", branchName: "${branch}" }, message: { headline: "seed: fixture anchor" }, fileChanges: { additions: [{ path: "${anchorFile}", contents: "${contentBase64}" }] }, expectedHeadOid: "${head}" }) { commit { oid } } }`,
    ]);
  }

  // Read the current branch tip — that's the fixture's baseOid going forward.
  const branchInfo = gh<{ commit: { sha: string } }>([
    'api',
    `repos/${OWNER}/${REPO}/branches/${branch}`,
  ]);
  return { baseOid: branchInfo.commit.sha, anchorFile, anchorLine };
}

function ensurePr(
  branch: string,
  name: string,
  login: string,
): { number: number; nodeId: string } {
  // List PRs targeting master from this branch.
  const list = gh<Array<{ number: number; node_id: string }>>([
    'api',
    `repos/${OWNER}/${REPO}/pulls?head=${OWNER}:${branch}&state=open`,
  ]);
  if (list.length > 0) {
    return { number: list[0].number, nodeId: list[0].node_id };
  }
  // Create.
  const created = gh<{ number: number; node_id: string }>([
    'api',
    '-X',
    'POST',
    `repos/${OWNER}/${REPO}/pulls`,
    '-f',
    `title=[e2e fixture, ${login}] ${name}`,
    '-f',
    `head=${branch}`,
    '-f',
    'base=master',
    '-f',
    'body=Generated by setup-real-e2e-fixtures.ts. Safe to delete if no longer needed.',
  ]);
  return { number: created.number, nodeId: created.node_id };
}

function main(): void {
  const login = viewerLogin();
  console.log(`[setup-real-e2e-fixtures] viewer=${login} repo=${OWNER}/${REPO}`);

  const fixtures: SandboxFixture[] = [];
  for (const name of FIXTURE_NAMES) {
    const branch = `e2e-real-${name}-fixture-${login}`;
    console.log(`[setup] processing ${branch}`);
    const { baseOid, anchorFile, anchorLine } = ensureBranchAtSeed(branch, name);
    const pr = ensurePr(branch, name, login);
    fixtures.push({
      name,
      branch,
      prNumber: pr.number,
      prNodeId: pr.nodeId,
      baseOid,
      anchorFile,
      anchorLine,
    });
    console.log(`[setup]   -> pr=#${pr.number} baseOid=${baseOid.slice(0, 8)}`);
  }

  const outPath = path.join('e2e', 'real', 'fixtures.json');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, JSON.stringify(fixtures, null, 2));
  console.log(`[setup] wrote ${outPath} (${fixtures.length} fixtures)`);
}

main();
